services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: meemprega
      POSTGRES_USER: meemprega
      POSTGRES_PASSWORD: meemprega
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    environment:
      POSTGRES_DB: meemprega_test
      POSTGRES_USER: meemprega
      POSTGRES_PASSWORD: meemprega
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test:
